### ISSUE TITLE
Add direct dependency on ignition-cmake2

### ISSUE THREAD

**Issue by traversaro** [conda-forge/libignition-common-feedstock#16]
Ignition-common depends on ignition-cmake2, as most (all?) of the other ignition libraries. This dependency should be explicitly listed (at the moment everything works thanks to the transitive dependency on ignition-cmake via ignition-math).

**Comment by Tobias-Fischer** [comment]
Would that only be a host dependency or also a run dependency?

**Comment by traversaro** [comment]
> 
> 
> Would that only be a host dependency or also a run dependency?

Just host.
