### ISSUE TITLE
patch Windows build and not to vendor the TinyXml2

### ISSUE THREAD

**Issue by seanyen** [conda-forge/libignition-common-feedstock#5]
`libignition-common` seems to vendor TinyXML2 for Windows build. And we should patch it and let it use the `conda-forge` one.

**Comment by Tobias-Fischer** [comment]
cc @traversaro

**Comment by traversaro** [comment]
Indeed: https://github.com/ignitionrobotics/ign-common/blob/ign-common3/CMakeLists.txt#L36 . I did not realized this, thanks @seanyen @Tobias-Fischer .

**Comment by traversaro** [comment]
Fix upstream: https://github.com/ignitionrobotics/ign-common/pull/116 . 
Patch to import:
https://patch-diff.githubusercontent.com/raw/ignitionrobotics/ign-common/pull/116.patch

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro. Would you be happy to open a PR here that includes this patch, and sets `USE_EXTERNAL_TINYXML2` to `ON` in the build script?

**Comment by traversaro** [comment]
Yes, I will handle that, thanks.

**Comment by Tobias-Fischer** [comment]
Kind reminder @traversaro :)
